#port ??
server:
  port: 9090

##DB Connection
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: spr
    password: spr

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false

logging.level:
  org:
    hibernate:
      SQL: debug
      type: trace
